<main class="flex justify-center items-center h-screen flex-col gap-7">
  <div class="bg-white p-8 rounded-lg shadow-lg text-center">
    <h1 class="text-2xl font-bold mb-4"><?= $title ?></h1>
    <p class="mb-4">Bem vindo ao sistema</p>
  </div>


  <form method="POST" action="<?= route('users.logout') ?>">
    <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-700">Logout</button>
  </form>
</main>
