<nav aria-label="Page navigation">
  <ul class="pagination justify-content-end">

    <?php if ($paginator->hasPreviousPage()) : ?>
    <li class="page-item">
      <a class="page-link" href="<?= route($paginator->getRouteName(), ['page' => $paginator->previousPage()]) ?>"
        aria-label="Go to previous page">Anterior</a>
    </li>
    <?php else : ?>
    <li class="page-item disabled">
      <a class="page-link" aria-label="Previous page is not available" aria-disabled="true">Anterior</a>
    </li>
    <?php endif; ?>

    <?php for ($page = 1; $page <= $paginator->totalOfPages(); $page++) : ?>
    <li class="page-item <?= $paginator->isPage($page) ? 'active' : '' ?>">
      <a class="page-link" href="<?= route($paginator->getRouteName(), ['page' => $page]) ?>"
        aria-label="Page <?= $page ?>">
        <?= $page ?>
      </a>
    </li>
    <?php endfor; ?>

    <?php if ($paginator->hasNextPage()) : ?>
    <li class="page-item">
      <a class="page-link" href="<?= route($paginator->getRouteName(), ['page' => $paginator->nextPage()]) ?>"
        aria-label="Go to next page">Próxima</a>
    </li>
    <?php else : ?>
    <li class="page-item disabled">
      <a class="page-link" aria-label="Next page is not available" aria-disabled="true">Próxima</a>
    </li>
    <?php endif; ?>
  </ul>
</nav>

<div class="d-flex justify-content-end">
  <?= $paginator->entriesInfo() ?>
</div>
