<?php foreach (\Lib\FlashMessage::get() as $type => $msg) : ?>
<div class="fixed top-0 left-0 w-full p-4 <?= $type === 'success' ? 'bg-green-500' : ($type === 'danger' ? 'bg-red-500' : 'bg-yellow-500') ?> text-white flex justify-between items-center text-2xl flash-message <?= $type ?> auto-fade"
    style="z-index: 10; pointer-events: none;">
    <div class="text-center w-full">
        <?= $msg ?>
    </div>
    <button type="button" class="text-white close-btn" onclick="this.parentElement.style.display='none';"
        aria-label="Close" style="pointer-events: auto;">&times;</button>
</div>
<?php endforeach; ?>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const flashMessages = document.querySelectorAll('.flash-message');
        if (flashMessages.length > 0) {
            setTimeout(function () {
                flashMessages.forEach(function (element) {
                    element.style.display = 'none';
                });
                // Disparar um evento personalizado quando as mensagens flash são ocultadas
                document.dispatchEvent(new CustomEvent('flashMessagesHidden'));
            }, 2000); // Reduzido para 2 segundos para facilitar os testes
        }
    });
</script>