<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TalentSoft -
    <?= $title ?>
  </title>
  <script src="/assets/js/application.js"></script>

  <script src="https://cdn.tailwindcss.com"></script>

  <link rel="stylesheet" href="/assets/css/application.css">

  <link rel="apple-touch-icon" href="/assets/images/defaults/favicon.ico">
  <link rel="icon" type="image/png" sizes="192x192" href="/assets/images/defaults/android-chrome-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/images/defaults/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/assets/images/defaults/favicon-16x16.png">
  <link rel="manifest" href="/assets/images/defaults/site.webmanifest">
  <link rel="icon" href="/assets/images/defaults/favicon.ico" type="image/x-icon">
</head>

<body>
  <nav class="bg-gray-800 text-white p-4">
    <div class="container mx-auto flex justify-between items-center">
      <div class="flex items-center">
        <span class="text-xl font-bold">TalentSoft</span>
      </div>
      <div class="flex items-center space-x-4">
        <span>Olá,
          <?= $this->currentUser()->name ?>
        </span>
        <a href="<?= route('auth.logout') ?>"
          class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Sair</a>
      </div>
    </div>
  </nav>

  <div class="fixed top-0 left-0 right-0 z-50">
    <?php foreach (\Lib\FlashMessage::get() as $type => $msg) : ?>
    <?php
      $colorClass = match($type) {
        'success' => 'bg-green-500',
        'danger' => 'bg-red-500',
        'warning' => 'bg-yellow-500',
        default => 'bg-blue-500',
      };
      ?>
    <div id="flash-message"
      class="<?= $colorClass ?> text-white p-4 text-center opacity-100 transition-opacity duration-700 ease-in-out"
      role="alert">
      <?= $msg ?>
      <button type="button" class="float-right font-bold" onclick="this.parentElement.remove();">&times;</button>
    </div>
    <?php endforeach; ?>
  </div>

  <script>
    // Remover automaticamente mensagens flash após 5 segundos
    document.addEventListener('DOMContentLoaded', function () {
      const flashMessages = document.querySelectorAll('#flash-message');
      if (flashMessages.length > 0) {
        setTimeout(function () {
          flashMessages.forEach(message => {
            message.style.opacity = '0';
            setTimeout(() => {
              message.remove();
            }, 700); // Tempo para a animação fade-out completar
          });
        }, 5000); // 5 segundos antes de iniciar o fade-out
      }
    });
  </script>

  <main class="container mx-auto mt-6 px-4">
    <?php require $view ?>
  </main>
</body>

</html>