<?php if (\Lib\Authentication\Auth::check() && \Lib\Authentication\Auth::user()->role === 'user'): ?>
<header class="bg-blue-600 text-white p-4">
  <h1 class="text-2xl font-bold mb-4">Bem-vindo à TalentSoft</h1>
  <nav aria-label="Main Navigation">
    <ul class="flex space-x-4">
      <li>
        <a href="<?= route('home') ?>" class="hover:underline">Home</a>
      </li>
      <li><a href="/" class="hover:underline">Perfil</a></li>
      <li><a href="/" class="hover:underline">Configurações</a></li>
      <li><a href="<?= route('users.list') ?>" class=" hover:underline">Listagem de Funcionários</a></li>
      <li>
        <form method="POST" action="<?= route('users.logout') ?>" class="inline">
          <button type="submit" class="hover:underline">Sair</button>
        </form>
      </li>
    </ul>
  </nav>
</header>
<?php endif; ?>

<?php if (\Lib\Authentication\Auth::check() && \Lib\Authentication\Auth::user()->role === 'admin'): ?>
<header class="bg-blue-700 text-white p-4">
  <h1 class="text-2xl font-bold mb-4">Bem-vindo à TalentSoft</h1>
  <nav aria-label="Main Navigation">
    <ul class="flex space-x-4">
      <li>
        <a href="<?= route('home.admin') ?>" class="hover:underline">Home</a>
      </li>
      <li><a href="/" class="hover:underline">Perfil</a></li>
      <li><a href="/" class="hover:underline">Configurações</a></li>
      <li><a href="<?= route('register.admin') ?>" class=" hover:underline">Cadastro de Funcionários</a></li>
      <li><a href="<?= route('users.list') ?>" class=" hover:underline">Listagem de Funcionários</a></li>
      <li>
        <form method="POST" action="<?= route('admin.logout') ?>" class="inline">
          <button type="submit" class="hover:underline">Sair</button>
        </form>
      </li>
    </ul>
  </nav>
</header>
<?php endif; ?>